package org.laplace.systems.eventsystem;

public enum EventTypes {
    PLAYER_MOVE_EVENT,
    PLAYER_WALL_COLLISION,
    PLAYER_START_BATTLE_EVENT,
    PLAYER_DEATH_EVENT,
    HOSTILE_MOB_DEATH_EVENT,
    PLAYER_BATTLE_EVENT,
    PLAYER_THROWING_COMBAT_DICES,
    DICE_THROWN,
    ROOM_CLEARED_FROM_HOSTILE_MOBS,
    ROOM_CLEARED_FROM_CHESTS
}
