package org.laplace.systems.modelmanager;

enum ChankType {
    NULL,
    ONE_UP_DOOR, ONE_LEFT_DOOR, ONE_RIGHT_DOOR, ONE_DOWN_DOOR,
    TWO_LEFT_RIGHT_DOOR, TWO_UP_DOWN_DOOR, TWO_LEFT_UP_DOOR, TWO_UP_RIGHT_DOOR, TWO_RIGHT_DOWN_DOOR, TWO_DOWN_LEFT_DOOR,
    THREE_F_UP_DOOR, THREE_F_RIGHT_DOOR, THREE_F_DOWN_DOOR, THREE_F_LEFT_DOOR,
    FOUR_DOOR
}

